20:35:28 29.01.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
20:35:28 29.01.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
20:35:28 29.01.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
20:35:28 29.01.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
20:35:29 29.01.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
20:35:29 29.01.2016 WARN  JdbcServicesImpl  configure:204 - HHH000342: Could not obtain connection to query metadata : Cannot create PoolableConnectionFactory (Access denied for user 'root'@'localhost' (using password: YES))
20:35:29 29.01.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
20:35:29 29.01.2016 INFO  LobCreatorBuilder  useContextualLobCreation:88 - HHH000422: Disabling contextual LOB creation as connection was null
20:35:29 29.01.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
20:40:23 29.01.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
20:40:23 29.01.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
20:40:23 29.01.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
20:40:23 29.01.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
20:40:24 29.01.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
20:40:24 29.01.2016 WARN  JdbcServicesImpl  configure:204 - HHH000342: Could not obtain connection to query metadata : Cannot create PoolableConnectionFactory (Access denied for user 'root'@'localhost' (using password: YES))
20:40:24 29.01.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
20:40:24 29.01.2016 INFO  LobCreatorBuilder  useContextualLobCreation:88 - HHH000422: Disabling contextual LOB creation as connection was null
20:40:24 29.01.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
13:08:43 30.01.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
13:08:44 30.01.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
13:08:44 30.01.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
13:08:44 30.01.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
13:08:44 30.01.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
13:08:44 30.01.2016 WARN  JdbcServicesImpl  configure:204 - HHH000342: Could not obtain connection to query metadata : Cannot create PoolableConnectionFactory (Access denied for user 'root'@'localhost' (using password: YES))
13:08:44 30.01.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
13:08:44 30.01.2016 INFO  LobCreatorBuilder  useContextualLobCreation:88 - HHH000422: Disabling contextual LOB creation as connection was null
13:08:45 30.01.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
11:40:21 31.01.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
11:40:22 31.01.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
11:40:22 31.01.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
11:40:22 31.01.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
11:40:22 31.01.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
11:40:22 31.01.2016 WARN  JdbcServicesImpl  configure:204 - HHH000342: Could not obtain connection to query metadata : Cannot create PoolableConnectionFactory (Access denied for user 'root'@'localhost' (using password: YES))
11:40:22 31.01.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
11:40:22 31.01.2016 INFO  LobCreatorBuilder  useContextualLobCreation:88 - HHH000422: Disabling contextual LOB creation as connection was null
11:40:22 31.01.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
12:39:44 31.01.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
12:39:44 31.01.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
12:39:44 31.01.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
12:39:44 31.01.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
12:39:44 31.01.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
12:39:45 31.01.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
12:39:45 31.01.2016 INFO  LobCreatorBuilder  useContextualLobCreation:97 - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [3] less than 4
12:39:45 31.01.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
13:16:46 31.01.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
13:16:46 31.01.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
13:16:46 31.01.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
13:16:46 31.01.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
13:16:46 31.01.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
13:16:47 31.01.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
13:16:47 31.01.2016 INFO  LobCreatorBuilder  useContextualLobCreation:97 - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [3] less than 4
13:16:47 31.01.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
16:38:42 31.01.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
16:38:42 31.01.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
16:38:42 31.01.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
16:38:42 31.01.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
16:38:42 31.01.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
16:38:43 31.01.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
16:38:43 31.01.2016 INFO  LobCreatorBuilder  useContextualLobCreation:97 - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [3] less than 4
16:38:43 31.01.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
16:41:22 31.01.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
16:41:22 31.01.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
16:41:22 31.01.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
16:41:22 31.01.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
16:41:22 31.01.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
16:41:23 31.01.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
16:41:23 31.01.2016 INFO  LobCreatorBuilder  useContextualLobCreation:97 - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [3] less than 4
16:41:23 31.01.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
16:41:24 31.01.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/AuthorHome!com.softserveinc.booklibrary.session.persist.home.impl.AuthorHomeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
16:41:24 31.01.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/AuthorFacade!com.softserveinc.booklibrary.session.persist.facade.impl.AuthorFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
16:41:24 31.01.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/BookHome!com.softserveinc.booklibrary.session.persist.home.impl.BookHomeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
16:41:24 31.01.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/BookFacade!com.softserveinc.booklibrary.session.persist.facade.impl.BookFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
16:41:24 31.01.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/ReviewHome!com.softserveinc.booklibrary.session.persist.home.impl.ReviewHomeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
16:41:24 31.01.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/ReviewFacade!com.softserveinc.booklibrary.session.persist.facade.impl.ReviewFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
16:41:25 31.01.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
16:41:25 31.01.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
16:41:27 31.01.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
16:41:30 31.01.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:06:49 01.02.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
17:06:50 01.02.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
17:06:50 01.02.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
17:06:50 01.02.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
17:06:50 01.02.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
17:06:50 01.02.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
17:06:50 01.02.2016 INFO  LobCreatorBuilder  useContextualLobCreation:97 - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [3] less than 4
17:06:50 01.02.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
17:06:51 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/AuthorHome!com.softserveinc.booklibrary.session.persist.home.impl.AuthorHomeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:06:51 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/AuthorFacade!com.softserveinc.booklibrary.session.persist.facade.impl.AuthorFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:06:51 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/BookHome!com.softserveinc.booklibrary.session.persist.home.impl.BookHomeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:06:51 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/BookFacade!com.softserveinc.booklibrary.session.persist.facade.impl.BookFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:06:51 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/ReviewHome!com.softserveinc.booklibrary.session.persist.home.impl.ReviewHomeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:06:51 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/ReviewFacade!com.softserveinc.booklibrary.session.persist.facade.impl.ReviewFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:06:52 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:06:52 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:06:53 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:06:54 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:54:31 01.02.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
17:54:31 01.02.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
17:54:31 01.02.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
17:54:31 01.02.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
17:54:31 01.02.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
17:54:32 01.02.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
17:54:32 01.02.2016 INFO  LobCreatorBuilder  useContextualLobCreation:97 - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [3] less than 4
17:54:32 01.02.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
17:54:33 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/AuthorHome!com.softserveinc.booklibrary.session.persist.home.impl.AuthorHomeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:54:33 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/AuthorFacade!com.softserveinc.booklibrary.session.persist.facade.impl.AuthorFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:54:33 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/BookHome!com.softserveinc.booklibrary.session.persist.home.impl.BookHomeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:54:33 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/BookFacade!com.softserveinc.booklibrary.session.persist.facade.impl.BookFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:54:33 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/ReviewHome!com.softserveinc.booklibrary.session.persist.home.impl.ReviewHomeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:54:33 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/ReviewFacade!com.softserveinc.booklibrary.session.persist.facade.impl.ReviewFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:54:33 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:54:33 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:54:34 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:54:35 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:55:52 01.02.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
17:55:52 01.02.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
17:55:52 01.02.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
17:55:52 01.02.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
17:55:52 01.02.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
17:55:52 01.02.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
17:55:52 01.02.2016 INFO  LobCreatorBuilder  useContextualLobCreation:97 - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [3] less than 4
17:55:52 01.02.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
17:55:53 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/AuthorHome!com.softserveinc.booklibrary.session.persist.home.impl.AuthorHomeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:55:53 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/AuthorFacade!com.softserveinc.booklibrary.session.persist.facade.impl.AuthorFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:55:53 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/BookHomeRemote!com.softserveinc.booklibrary.session.persist.home.BookHomeRemoteRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:55:53 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/BookFacade!com.softserveinc.booklibrary.session.persist.facade.impl.BookFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:55:53 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/ReviewHome!com.softserveinc.booklibrary.session.persist.home.impl.ReviewHomeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:55:53 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/ReviewFacade!com.softserveinc.booklibrary.session.persist.facade.impl.ReviewFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:55:53 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:55:53 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:55:54 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:55:55 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:57:03 01.02.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
17:57:03 01.02.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
17:57:03 01.02.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
17:57:03 01.02.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
17:57:03 01.02.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
17:57:04 01.02.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
17:57:04 01.02.2016 INFO  LobCreatorBuilder  useContextualLobCreation:97 - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [3] less than 4
17:57:04 01.02.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
17:57:05 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/AuthorHomeRemote!com.softserveinc.booklibrary.session.persist.home.AuthorHomeRemoteRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:57:05 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/AuthorFacadeRemote!com.softserveinc.booklibrary.session.persist.facade.AuthorFacadeRemoteRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:57:05 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/BookHomeRemote!com.softserveinc.booklibrary.session.persist.home.BookHomeRemoteRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:57:05 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/BookFacadeRemote!com.softserveinc.booklibrary.session.persist.facade.BookFacadeRemoteRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:57:05 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/ReviewHome!com.softserveinc.booklibrary.session.persist.home.impl.ReviewHomeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:57:05 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/ReviewFacade!com.softserveinc.booklibrary.session.persist.facade.impl.ReviewFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:57:05 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:57:05 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:57:06 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:57:07 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:59:18 01.02.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
17:59:19 01.02.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
17:59:19 01.02.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
17:59:19 01.02.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
17:59:19 01.02.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
17:59:19 01.02.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
17:59:19 01.02.2016 INFO  LobCreatorBuilder  useContextualLobCreation:97 - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [3] less than 4
17:59:19 01.02.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
17:59:20 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/AuthorHome!com.softserveinc.booklibrary.session.persist.home.impl.AuthorHomeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:59:20 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/AuthorFacade!com.softserveinc.booklibrary.session.persist.facade.impl.AuthorFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:59:20 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/BookHome!com.softserveinc.booklibrary.session.persist.home.impl.BookHomeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:59:20 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/BookFacade!com.softserveinc.booklibrary.session.persist.facade.impl.BookFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:59:20 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/ReviewHome!com.softserveinc.booklibrary.session.persist.home.impl.ReviewHomeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:59:20 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/ReviewFacade!com.softserveinc.booklibrary.session.persist.facade.impl.ReviewFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
17:59:20 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:59:20 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:59:21 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
17:59:22 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:02:44 01.02.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
18:02:44 01.02.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
18:02:44 01.02.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
18:02:44 01.02.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
18:02:44 01.02.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
18:02:44 01.02.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
18:02:44 01.02.2016 INFO  LobCreatorBuilder  useContextualLobCreation:97 - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [3] less than 4
18:02:44 01.02.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
18:02:45 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/AuthorFacade!com.softserveinc.booklibrary.session.persist.facade.impl.AuthorFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
18:02:45 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/BookFacade!com.softserveinc.booklibrary.session.persist.facade.impl.BookFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
18:02:45 01.02.2016 ERROR TestHelper  getRemoteBean:79 - Remote bean  could not found
javax.naming.NameNotFoundException: Name "global/BookLibrary-cdi/ReviewFacade!com.softserveinc.booklibrary.session.persist.facade.impl.ReviewFacadeRemote" not found.
	at org.apache.openejb.core.ivm.naming.IvmContext.federate(IvmContext.java:199)
	at org.apache.openejb.core.ivm.naming.IvmContext.lookup(IvmContext.java:151)
	at org.apache.xbean.naming.context.ContextFlyweight.lookup(ContextFlyweight.java:55)
	at com.softserveinc.model.util.TestHelper.getRemoteBean(TestHelper.java:76)
	at com.softserveinc.model.util.BaseTest.getRemoteBeans(BaseTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
18:02:45 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:02:45 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:02:46 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:02:47 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:02:49 01.02.2016 INFO  BookHome  create:40 - Entity Book{idBook=fcad56d1-c953-4493-9774-a1fe48b420ea, bookName=Windows, createdDate=Mon Feb 01 18:02:49 EET 2016, isbn=222-11-112-1, publisher=Japan, yearPublished=2015} has been successfully created
18:02:49 01.02.2016 INFO  BookHome  create:40 - Entity Book{idBook=bfe1601c-e6ec-491e-9fc6-610a22d5d09c, bookName=Windows, createdDate=Mon Feb 01 18:02:49 EET 2016, isbn=111-11-111-1, publisher=Japan, yearPublished=2015} has been successfully created
18:02:49 01.02.2016 WARN  SqlExceptionHelper  logExceptions:144 - SQL Error: 1062, SQLState: 23000
18:02:49 01.02.2016 ERROR SqlExceptionHelper  logExceptions:146 - Duplicate entry '111-11-111-1' for key 'isbn'
18:02:49 01.02.2016 INFO  AbstractBatchImpl  release:208 - HHH000010: On release of batch it still contained JDBC statements
18:02:49 01.02.2016 WARN  Transaction  beforeCompletion:529 - Unexpected exception from beforeCompletion; transaction will roll back
javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1683)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl$CallbackExceptionMapperImpl.mapManagedFlushFailure(AbstractEntityManagerImpl.java:1882)
	at org.hibernate.engine.transaction.synchronization.internal.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:115)
	at org.hibernate.engine.transaction.synchronization.internal.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:50)
	at org.apache.geronimo.transaction.manager.TransactionImpl.beforeCompletion(TransactionImpl.java:527)
	at org.apache.geronimo.transaction.manager.TransactionImpl.beforeCompletion(TransactionImpl.java:511)
	at org.apache.geronimo.transaction.manager.TransactionImpl.beforePrepare(TransactionImpl.java:413)
	at org.apache.geronimo.transaction.manager.TransactionImpl.commit(TransactionImpl.java:262)
	at org.apache.geronimo.transaction.manager.TransactionManagerImpl.commit(TransactionManagerImpl.java:252)
	at org.apache.openejb.core.transaction.JtaTransactionPolicy.completeTransaction(JtaTransactionPolicy.java:331)
	at org.apache.openejb.core.transaction.TxRequired.commit(TxRequired.java:76)
	at org.apache.openejb.core.transaction.EjbTransactionUtil.afterInvoke(EjbTransactionUtil.java:77)
	at org.apache.openejb.core.stateless.StatelessContainer._invoke(StatelessContainer.java:246)
	at org.apache.openejb.core.stateless.StatelessContainer.invoke(StatelessContainer.java:194)
	at org.apache.openejb.core.ivm.EjbObjectProxyHandler.synchronizedBusinessMethod(EjbObjectProxyHandler.java:308)
	at org.apache.openejb.core.ivm.EjbObjectProxyHandler.businessMethod(EjbObjectProxyHandler.java:303)
	at org.apache.openejb.core.ivm.EjbObjectProxyHandler._invoke(EjbObjectProxyHandler.java:92)
	at org.apache.openejb.core.ivm.BaseEjbProxyHandler.invoke(BaseEjbProxyHandler.java:322)
	at com.sun.proxy.$Proxy89.create(Unknown Source)
	at com.softserveinc.model.persist.home.BookHomeTest.testCreateBookWithAlreadyExistISBN(BookHomeTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:72)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:62)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3124)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3581)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:104)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:463)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:349)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1222)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425)
	at org.hibernate.engine.transaction.synchronization.internal.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:110)
	... 41 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '111-11-111-1' for key 'isbn'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
	... 52 more
18:02:49 01.02.2016 INFO  AuthorHome  findByID:66 - Entity Author{idAuthor=a1, createdDate=2015-11-10 11:30:15.0, firstName=Raul, secondName=Garsia} has been successfully found by id = a1
18:02:49 01.02.2016 INFO  AuthorHome  findByID:66 - Entity Author{idAuthor=a9, createdDate=2015-10-29 10:28:15.0, firstName=Peter, secondName=McCalcin} has been successfully found by id = a9
18:02:49 01.02.2016 INFO  BookHome  create:40 - Entity Book{idBook=b6f1fe35-7d8c-4840-b105-e615c4cd1208, bookName=Windows 8.1 New, createdDate=Mon Feb 01 18:02:49 EET 2016, isbn=111-122-32-2, publisher=Japan, yearPublished=2015, authors=[Author{idAuthor=a9, createdDate=2015-10-29 10:28:15.0, firstName=Peter, secondName=McCalcin}, Author{idAuthor=a1, createdDate=2015-11-10 11:30:15.0, firstName=Raul, secondName=Garsia}]} has been successfully created
18:02:49 01.02.2016 INFO  AuthorHome  findByID:66 - Entity Author{idAuthor=a1, createdDate=2015-11-10 11:30:15.0, firstName=Raul, secondName=Garsia} has been successfully found by id = a1
18:02:49 01.02.2016 INFO  AuthorHome  findByID:66 - Entity Author{idAuthor=a4, createdDate=2015-10-29 10:28:15.0, firstName=Greg, secondName=Blou} has been successfully found by id = a4
18:02:49 01.02.2016 INFO  BookHome  findByID:59 - Entity Book{idBook=b5, bookName=Spring, createdDate=2015-10-29 10:28:15.0, isbn=111-11-111-5, publisher=England, yearPublished=2015, authors=[Author{idAuthor=a1, createdDate=2015-11-10 11:30:15.0, firstName=Raul, secondName=Garsia}]} has been successfully found by id = b5
18:02:49 01.02.2016 INFO  AuthorHome  findByID:66 - Entity Author{idAuthor=a5, createdDate=2015-11-10 11:30:15.0, firstName=Sam, secondName=Black} has been successfully found by id = a5
18:02:49 01.02.2016 INFO  AuthorHome  findByID:66 - Entity Author{idAuthor=a6, createdDate=2015-12-14 11:55:15.0, firstName=Vlad, secondName=White} has been successfully found by id = a6
18:02:49 01.02.2016 INFO  AuthorHome  findByID:66 - Entity Author{idAuthor=a7, createdDate=2015-12-14 11:22:15.0, firstName=Oliver, secondName=Blue} has been successfully found by id = a7
18:02:49 01.02.2016 INFO  AuthorHome  findByID:66 - Entity Author{idAuthor=a2, createdDate=2015-12-14 11:55:15.0, firstName=Cristian, secondName=Ronaldo} has been successfully found by id = a2
18:02:50 01.02.2016 INFO  BookHome  update:45 - Entity Book{idBook=b5, bookName=New Name, createdDate=2015-10-29 10:28:15.0, isbn=777-777-777-7, publisher=publisher, yearPublished=1990, authors=[Author{idAuthor=a7, createdDate=2015-12-14 11:22:15.0, firstName=Oliver, secondName=Blue}, Author{idAuthor=a6, createdDate=2015-12-14 11:55:15.0, firstName=Vlad, secondName=White}, Author{idAuthor=a2, createdDate=2015-12-14 11:55:15.0, firstName=Cristian, secondName=Ronaldo}, Author{idAuthor=a5, createdDate=2015-11-10 11:30:15.0, firstName=Sam, secondName=Black}]} has been successfully updated
18:02:50 01.02.2016 INFO  BookHome  findByID:59 - Entity Book{idBook=b5, bookName=New Name, createdDate=2015-10-29 10:28:15.0, isbn=777-777-777-7, publisher=publisher, yearPublished=1990, authors=[Author{idAuthor=a7, createdDate=2015-12-14 11:22:15.0, firstName=Oliver, secondName=Blue}, Author{idAuthor=a6, createdDate=2015-12-14 11:55:15.0, firstName=Vlad, secondName=White}, Author{idAuthor=a2, createdDate=2015-12-14 11:55:15.0, firstName=Cristian, secondName=Ronaldo}, Author{idAuthor=a5, createdDate=2015-11-10 11:30:15.0, firstName=Sam, secondName=Black}]} has been successfully found by id = b5
18:12:36 01.02.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
18:12:36 01.02.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
18:12:36 01.02.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
18:12:36 01.02.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
18:12:36 01.02.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
18:12:37 01.02.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
18:12:37 01.02.2016 INFO  LobCreatorBuilder  useContextualLobCreation:97 - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [3] less than 4
18:12:37 01.02.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
18:12:38 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:12:38 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:12:39 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:12:40 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:12:42 01.02.2016 INFO  BookHome  create:42 - Entity Book{idBook=04707851-5b1d-4d24-89ab-5145ff790381, bookName=Windows, createdDate=Mon Feb 01 18:12:42 EET 2016, isbn=222-11-112-1, publisher=Japan, yearPublished=2015} has been successfully created
18:12:42 01.02.2016 INFO  BookHome  create:42 - Entity Book{idBook=feb30900-3910-464d-86d1-a6ae26113a1c, bookName=Windows, createdDate=Mon Feb 01 18:12:42 EET 2016, isbn=111-11-111-1, publisher=Japan, yearPublished=2015} has been successfully created
18:12:42 01.02.2016 WARN  SqlExceptionHelper  logExceptions:144 - SQL Error: 1062, SQLState: 23000
18:12:42 01.02.2016 ERROR SqlExceptionHelper  logExceptions:146 - Duplicate entry '111-11-111-1' for key 'isbn'
18:12:42 01.02.2016 INFO  AbstractBatchImpl  release:208 - HHH000010: On release of batch it still contained JDBC statements
18:12:42 01.02.2016 WARN  Transaction  beforeCompletion:529 - Unexpected exception from beforeCompletion; transaction will roll back
javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1683)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl$CallbackExceptionMapperImpl.mapManagedFlushFailure(AbstractEntityManagerImpl.java:1882)
	at org.hibernate.engine.transaction.synchronization.internal.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:115)
	at org.hibernate.engine.transaction.synchronization.internal.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:50)
	at org.apache.geronimo.transaction.manager.TransactionImpl.beforeCompletion(TransactionImpl.java:527)
	at org.apache.geronimo.transaction.manager.TransactionImpl.beforeCompletion(TransactionImpl.java:511)
	at org.apache.geronimo.transaction.manager.TransactionImpl.beforePrepare(TransactionImpl.java:413)
	at org.apache.geronimo.transaction.manager.TransactionImpl.commit(TransactionImpl.java:262)
	at org.apache.geronimo.transaction.manager.TransactionManagerImpl.commit(TransactionManagerImpl.java:252)
	at org.apache.openejb.core.transaction.JtaTransactionPolicy.completeTransaction(JtaTransactionPolicy.java:331)
	at org.apache.openejb.core.transaction.TxRequired.commit(TxRequired.java:76)
	at org.apache.openejb.core.transaction.EjbTransactionUtil.afterInvoke(EjbTransactionUtil.java:77)
	at org.apache.openejb.core.stateless.StatelessContainer._invoke(StatelessContainer.java:246)
	at org.apache.openejb.core.stateless.StatelessContainer.invoke(StatelessContainer.java:194)
	at org.apache.openejb.core.ivm.EjbObjectProxyHandler.synchronizedBusinessMethod(EjbObjectProxyHandler.java:308)
	at org.apache.openejb.core.ivm.EjbObjectProxyHandler.businessMethod(EjbObjectProxyHandler.java:303)
	at org.apache.openejb.core.ivm.EjbObjectProxyHandler._invoke(EjbObjectProxyHandler.java:92)
	at org.apache.openejb.core.ivm.BaseEjbProxyHandler.invoke(BaseEjbProxyHandler.java:322)
	at com.sun.proxy.$Proxy90.create(Unknown Source)
	at com.softserveinc.model.persist.home.BookHomeTest.testCreateBookWithAlreadyExistISBN(BookHomeTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:72)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:62)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3124)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3581)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:104)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:463)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:349)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1222)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425)
	at org.hibernate.engine.transaction.synchronization.internal.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:110)
	... 41 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '111-11-111-1' for key 'isbn'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
	... 52 more
18:12:42 01.02.2016 INFO  AuthorHome  findByID:68 - Entity Author{idAuthor=a1, createdDate=2015-11-10 11:30:15.0, firstName=Raul, secondName=Garsia} has been successfully found by id = a1
18:12:42 01.02.2016 INFO  AuthorHome  findByID:68 - Entity Author{idAuthor=a9, createdDate=2015-10-29 10:28:15.0, firstName=Peter, secondName=McCalcin} has been successfully found by id = a9
18:12:42 01.02.2016 INFO  BookHome  create:42 - Entity Book{idBook=61e19f04-a8bf-4141-96b6-4d8fc7f4b3c8, bookName=Windows 8.1 New, createdDate=Mon Feb 01 18:12:42 EET 2016, isbn=111-122-32-2, publisher=Japan, yearPublished=2015, authors=[Author{idAuthor=a9, createdDate=2015-10-29 10:28:15.0, firstName=Peter, secondName=McCalcin}, Author{idAuthor=a1, createdDate=2015-11-10 11:30:15.0, firstName=Raul, secondName=Garsia}]} has been successfully created
18:12:42 01.02.2016 INFO  AuthorHome  findByID:68 - Entity Author{idAuthor=a1, createdDate=2015-11-10 11:30:15.0, firstName=Raul, secondName=Garsia} has been successfully found by id = a1
18:12:42 01.02.2016 INFO  AuthorHome  findByID:68 - Entity Author{idAuthor=a4, createdDate=2015-10-29 10:28:15.0, firstName=Greg, secondName=Blou} has been successfully found by id = a4
18:12:42 01.02.2016 INFO  BookHome  findByID:61 - Entity Book{idBook=b5, bookName=Spring, createdDate=2015-10-29 10:28:15.0, isbn=111-11-111-5, publisher=England, yearPublished=2015, authors=[Author{idAuthor=a1, createdDate=2015-11-10 11:30:15.0, firstName=Raul, secondName=Garsia}]} has been successfully found by id = b5
18:12:42 01.02.2016 INFO  AuthorHome  findByID:68 - Entity Author{idAuthor=a5, createdDate=2015-11-10 11:30:15.0, firstName=Sam, secondName=Black} has been successfully found by id = a5
18:12:42 01.02.2016 INFO  AuthorHome  findByID:68 - Entity Author{idAuthor=a6, createdDate=2015-12-14 11:55:15.0, firstName=Vlad, secondName=White} has been successfully found by id = a6
18:12:42 01.02.2016 INFO  AuthorHome  findByID:68 - Entity Author{idAuthor=a7, createdDate=2015-12-14 11:22:15.0, firstName=Oliver, secondName=Blue} has been successfully found by id = a7
18:12:42 01.02.2016 INFO  AuthorHome  findByID:68 - Entity Author{idAuthor=a2, createdDate=2015-12-14 11:55:15.0, firstName=Cristian, secondName=Ronaldo} has been successfully found by id = a2
18:12:42 01.02.2016 INFO  BookHome  update:47 - Entity Book{idBook=b5, bookName=New Name, createdDate=2015-10-29 10:28:15.0, isbn=777-777-777-7, publisher=publisher, yearPublished=1990, authors=[Author{idAuthor=a7, createdDate=2015-12-14 11:22:15.0, firstName=Oliver, secondName=Blue}, Author{idAuthor=a6, createdDate=2015-12-14 11:55:15.0, firstName=Vlad, secondName=White}, Author{idAuthor=a2, createdDate=2015-12-14 11:55:15.0, firstName=Cristian, secondName=Ronaldo}, Author{idAuthor=a5, createdDate=2015-11-10 11:30:15.0, firstName=Sam, secondName=Black}]} has been successfully updated
18:12:42 01.02.2016 INFO  BookHome  findByID:61 - Entity Book{idBook=b5, bookName=New Name, createdDate=2015-10-29 10:28:15.0, isbn=777-777-777-7, publisher=publisher, yearPublished=1990, authors=[Author{idAuthor=a7, createdDate=2015-12-14 11:22:15.0, firstName=Oliver, secondName=Blue}, Author{idAuthor=a6, createdDate=2015-12-14 11:55:15.0, firstName=Vlad, secondName=White}, Author{idAuthor=a2, createdDate=2015-12-14 11:55:15.0, firstName=Cristian, secondName=Ronaldo}, Author{idAuthor=a5, createdDate=2015-11-10 11:30:15.0, firstName=Sam, secondName=Black}]} has been successfully found by id = b5
18:14:56 01.02.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
18:14:56 01.02.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
18:14:56 01.02.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
18:14:56 01.02.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
18:14:57 01.02.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
18:14:57 01.02.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
18:14:57 01.02.2016 INFO  LobCreatorBuilder  useContextualLobCreation:97 - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [3] less than 4
18:14:57 01.02.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
18:14:58 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:14:58 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:14:59 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:15:00 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:15:02 01.02.2016 INFO  BookHome  create:42 - Entity Book{idBook=40a11cd2-86df-40b6-912f-a407e940ea16, bookName=Windows, createdDate=Mon Feb 01 18:15:02 EET 2016, isbn=222-11-112-1, publisher=Japan, yearPublished=2015} has been successfully created
18:15:38 01.02.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
18:15:38 01.02.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
18:15:38 01.02.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
18:15:38 01.02.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
18:15:38 01.02.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
18:15:38 01.02.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
18:15:38 01.02.2016 INFO  LobCreatorBuilder  useContextualLobCreation:97 - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [3] less than 4
18:15:38 01.02.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
18:15:39 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:15:40 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:15:40 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:15:41 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:15:43 01.02.2016 INFO  BookHome  create:42 - Entity Book{idBook=d6f183e6-5012-4766-9860-e0c49047fbf5, bookName=Windows, createdDate=Mon Feb 01 18:15:43 EET 2016, isbn=222-11-112-1, publisher=Japan, yearPublished=2015} has been successfully created
18:16:40 01.02.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
18:16:40 01.02.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
18:16:40 01.02.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
18:16:40 01.02.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
18:16:40 01.02.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
18:16:41 01.02.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
18:16:41 01.02.2016 INFO  LobCreatorBuilder  useContextualLobCreation:97 - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [3] less than 4
18:16:41 01.02.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
18:16:42 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:16:42 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:16:43 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:16:44 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:16:46 01.02.2016 INFO  BookHome  create:42 - Entity Book{idBook=8db08dd4-9bcd-47ce-82b1-6e84ce050d10, bookName=Windows, createdDate=Mon Feb 01 18:16:46 EET 2016, isbn=222-11-112-1, publisher=Japan, yearPublished=2015} has been successfully created
18:19:00 01.02.2016 INFO  LogHelper  logPersistenceUnitInformation:46 - HHH000204: Processing PersistenceUnitInfo [
	name: primary
	...]
18:19:00 01.02.2016 INFO  Version  logVersion:54 - HHH000412: Hibernate Core {4.3.6.Final}
18:19:00 01.02.2016 INFO  Environment  <clinit>:239 - HHH000206: hibernate.properties not found
18:19:00 01.02.2016 INFO  Environment  buildBytecodeProvider:346 - HHH000021: Bytecode provider name : javassist
18:19:00 01.02.2016 INFO  Version  <clinit>:66 - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
18:19:00 01.02.2016 INFO  Dialect  <init>:145 - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
18:19:00 01.02.2016 INFO  LobCreatorBuilder  useContextualLobCreation:97 - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [3] less than 4
18:19:00 01.02.2016 INFO  ASTQueryTranslatorFactory  <init>:47 - HHH000397: Using ASTQueryTranslatorFactory
18:19:01 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:19:01 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:19:02 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:19:03 01.02.2016 WARN  AbstractTableMetaData  getDataTypeFactory:166 - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
18:19:05 01.02.2016 INFO  BookHome  create:42 - Entity Book{idBook=188f6cab-ea6e-4de8-bad0-30599271a2c2, bookName=Windows, createdDate=Mon Feb 01 18:19:05 EET 2016, isbn=222-11-112-1, publisher=Japan, yearPublished=2015} has been successfully created
