<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ARBON" name="Default test" tests="7" failures="1" timestamp="24 Jan 2016 15:18:00 GMT" time="6.37" errors="0">
  <testcase name="testCreateBook" time="0.315" classname="com.softserveinc.model.persist.home.BookHomeTest"/>
  <testcase name="testCreateBookWithAlreadyExistISBN" time="0.07" classname="com.softserveinc.model.persist.home.BookHomeTest"/>
  <testcase name="testCreateBookWithAuthors" time="0.27" classname="com.softserveinc.model.persist.home.BookHomeTest"/>
  <testcase name="testUpdateBook" time="0.552" classname="com.softserveinc.model.persist.home.BookHomeTest"/>
  <testcase name="testDeleteBook" time="0.36" classname="com.softserveinc.model.persist.home.BookHomeTest">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;58&amp;gt; but was:&amp;lt;59&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<58> but was:<59>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.softserveinc.model.persist.home.BookHomeTest.testDeleteBook(BookHomeTest.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- testDeleteBook -->
  <testcase name="testFindAllBooks" time="0.0" classname="com.softserveinc.model.persist.home.BookHomeTest">
    <skipped/>
  </testcase> <!-- testFindAllBooks -->
  <testcase name="testFindByIdBook" time="0.0" classname="com.softserveinc.model.persist.home.BookHomeTest">
    <skipped/>
  </testcase> <!-- testFindByIdBook -->
</testsuite> <!-- Default test -->
